### ISSUE TITLE
推荐给项目加上 CC 证书

### ISSUE THREAD

**Issue by jtr109** [Lihaogx/graph-note-of-greek-myth#1]
如果认同相关条款的话，推荐给项目加上 [CC](https://creativecommons.org/licenses/by/4.0/deed.zh) 证书。这样可以更准确地声明自己的版权。

附 Wiki 链接供参考：[知识共享许可协议 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E7%9F%A5%E8%AF%86%E5%85%B1%E4%BA%AB%E8%AE%B8%E5%8F%AF%E5%8D%8F%E8%AE%AE)

**Comment by Lihaogx** [comment]
谢谢，我正在看这个，还没搞太明白它的发布方式和在大陆的法律效力

**Comment by jtr109** [comment]
> 谢谢，我正在看这个，还没搞太明白它的发布方式和在大陆的法律效力

如果是想了解怎么在 GitHub 中添加证书，可以参考[这篇文档](https://docs.github.com/cn/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)。

希望了解 CC 证书，可以参考这篇有个大概了解：[谈谈创作共用许可证（Creative Commons licenses） - 阮一峰的网络日志](https://www.ruanyifeng.com/blog/2008/04/creative_commons_licenses.html)。

希望对你有帮助。

在国内的法律效力这方面我没有仔细研究过，如果有时间，我会再找找有没有相关资料进行补充。

**Comment by Lihaogx** [comment]
收到，太感谢了
