### ISSUE TITLE
你这仓库怎么这么大

### ISSUE THREAD

**Issue by linonetwo** [Lihaogx/graph-note-of-greek-myth#3]
![](https://user-images.githubusercontent.com/3746270/147341469-4cc0334d-4130-4503-9be4-3ba40b77147c.png)

建议使用 [https://onetwo.ren/wiki/#%E6%9F%A5%E7%9C%8BGit%E4%BB%93%E5%BA%93%E9%87%8C%E7%9A%84%E5%A4%A7%E6%96%87%E4%BB%B6](https://onetwo.ren/wiki/#%E6%9F%A5%E7%9C%8BGit%E4%BB%93%E5%BA%93%E9%87%8C%E7%9A%84%E5%A4%A7%E6%96%87%E4%BB%B6) 清一下

**Comment by Lihaogx** [comment]
因为有很多图片....

**Comment by linonetwo** [comment]
Oh, 还以为你是保存了很多历史版本和历史 HTML 呢
